import Navbar from '@/components/layouts/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import Footer from '@/components/layouts/Footer'

const roboto = Roboto({ subsets: ['latin'], weight: ['100','300','400','500','700','100'] })

export const metadata: Metadata = {
  title: 'DApp',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navbar/>
          {children}
        <Footer/>
      </body>
    </html>
  )
}
